version: '3.8'
services:
  fincheck-dev-database:
    container_name: fincheck-dev-database
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dev-db
    networks:
      - system-network

networks:
  system-network:
